# Generated by Django 4.2 on 2023-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
